# https://www.stormkit.io/docs/deployments/configuration/angular
# > nav@6.0.1 setup /home/app/repo
app:
-redirects:
    -from: /*
     to: /dist/index.html
     assets: false
     #replace: false
     #cdn: false

