# https://www.stormkit.io/docs/deployments/configuration/angular
# > nav@6.0.1 setup /home/app/repo
app:
- redirects:
    - from: /*
     to: /dist
     assets: true
     #replace: false
     #cdn: false

